### ISSUE TITLE
Question about visibleTimeStart

### ISSUE THREAD

**Issue by Wax6610** [namespace-ee/react-calendar-timeline#511]
Hello and thank you very much for this cool component !

I have question about how to use visibleTimeStart and defaultTimeStart. 
In my project i want to limit Timeline just for one day. I set visibleTimeStart(or defaultTimeStart), but after component render first time i see a day before visibleTimeStart(or defaultTimeStart). Once i force to re-render component (for example just resize browser window) i see the right date. I tried to use fixed date or just "today" date but got the same problem.
How can i fix it or force component to update again after start ?

First render
![1](https://user-images.githubusercontent.com/26425381/53010449-0146f900-344f-11e9-8ab6-29f13a4e4bb0.png)
After re-render
![2](https://user-images.githubusercontent.com/26425381/53010460-0b68f780-344f-11e9-8d06-457b2f8a96ad.png)

**Comment by Ilaiwi** [comment]
@KuroiNeko6610 you need to set both the visibleTimeStart and visibleTimeEnd. Try it and let me know if this fixed your issue.

**Comment by florinciubotariu** [comment]
@Ilaiwi Unfortunately the issue still persists even after setting those props.

**Comment by Ilaiwi** [comment]
@florinciubotariu please provide a codesandbox example so I can help you

**Comment by Ilaiwi** [comment]
@florinciubotariu @Wax6610 apparently this was a bug that i didn't know about. I fixed it in 0.26.6
example here
https://codesandbox.io/s/timeline-demo-controlled-visible-time-no-scroll-659jb

**Comment by shuqingw** [comment]
question still exists in example [https://codesandbox.io/s/timeline-demo-controlled-visible-time-no-scroll-659jb](url)
