### ISSUE TITLE
Question: Specific timeframe using visibleTimeStart and visibleTimeEnd

### ISSUE THREAD

**Issue by vititu** [namespace-ee/react-calendar-timeline#537]
Using `visibleTimeStart` and `visibleTimeEnd` is possible to set a specific timeframe, but when mouse scrolling the header correctly stays put but the items scroll, is there a way to prevent that? To only be able to scroll if zooming in, for example?

Here is an example: https://codesandbox.io/s/z678yrr23

**Comment by sexta13** [comment]
did you get any solution?

**Comment by Ilaiwi** [comment]
I am releasing a bug fix for this today. I will close the issue and give a working example when the fix is released

**Comment by Aleksis92** [comment]
Still the same issue.
If you look at your example https://codesandbox.io/s/timeline-demo-controlled-visible-time-no-scroll-659jb?file=/CustomTimeline.jsx - you set visibleTime properties to 2 days range, but we can see the third day, and header units doesn't move with canvas when we scroll it by mouse or zooming.
Do you have any solution to show on timeline exactly provided visible time with correct scrolling (including header) and zoom?
